// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto_dotnet_sql.Models;

#nullable disable

namespace projeto_dotnet_sql.Migrations
{
    [DbContext(typeof(ConcessionariaContext))]
    partial class ConcessionariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projeto_dotnet_sql.Models.Veiculo", b =>
                {
                    b.Property<string>("NumeroChassi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Ano")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<double>("Quilometragem")
                        .HasColumnType("float");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<string>("VersaoSistema")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("NumeroChassi");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("projeto_dotnet_sql.Models.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedorId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("SalarioMinimo")
                        .HasColumnType("float");

                    b.HasKey("VendedorId");

                    b.ToTable("Vendedores");
                });
#pragma warning restore 612, 618
        }
    }
}
